### ISSUE TITLE
Translation into portuguese (Brazil)

### ISSUE THREAD

**Issue by lsprandel** [elecfreaks/pxt-cutebot#14]
Hello,
I would be very happy to see my students using this incredible project in Portuguese as well.
That's why I'm sending you the translated json files.

Thank you very much and congratulations on your work.
[cutebot-jsdoc-strings.json](https://github.com/user-attachments/files/17079893/cutebot-jsdoc-strings.json)
[cutebot-strings.json](https://github.com/user-attachments/files/17079894/cutebot-strings.json)

**Comment by elecfreaks1** [comment]
Thank you very much for providing the translated JSON files. We have successfully integrated them into the project. You can now try updating the cuteBot package in MakeCode to the latest version and check if the translations are correctly applied.
