### ISSUE TITLE
If you use the full power on the motors function in cutebot, it will drift to the right

### ISSUE THREAD

**Issue by Kakcalu13** [elecfreaks/pxt-cutebot#16]
The code here:

```
cuteBot.motors(99, 99)

def on_forever():
    pass
basic.forever(on_forever)
```

I was expecting it to drive straight forward, but it ended up drifting to the right.

I have 3 microbits and they all are like that.

**Comment by Kakcalu13** [comment]
If I put like this:

```
cuteBot.motors(90, 99)
```

It is considered as forward. 

Can we fix this?

**Comment by elecfreaks1** [comment]
Thanks for pointing that out. You're right; the motors can have speed differences up to 10%, which causes the drift. To get both motors running perfectly in sync, we'd need encoders or similar modules for feedback adjustment, which the current CuteBot doesn't support.

For now, tweaking the motor speeds like you did is a good workaround. We'll keep your feedback in mind for future improvements!
