### ISSUE TITLE
问题 

### ISSUE THREAD

**Issue by Kakcalu13** [elecfreaks/pxt-cutebot#7]
我对micro:bit酷比特（Cutebot）有一个问题。你知道它使用的是什么类型的橡胶轮子吗？它具有良好的摩擦力，我想知道具体使用的材料，这样我就可以使用Elecfreaks的零件在自定义车身上添加更多的轮子。

**Comment by Kakcalu13** [comment]
bump

**Comment by elecfreaks1** [comment]
The wheels used on the micro:bit CuteBot are standard PP (Polypropylene) plastic wheels that we source from our supplier. They provide good friction.
